name: pembs_produce
publish_to: 'none'
version: 0.1.3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.6.2
  google_maps_flutter_platform_interface: ^2.4.3
  google_places_flutter: ^2.0.8
  image_picker: ^1.0.7
  in_app_update: ^4.2.2
  permission_handler: ^11.3.0
  resend: ^1.0.0
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/.env
    - assets/no_image_placeholder.png  

  uses-material-design: true
